version: '2'
services:
    apphair-app:
        image: apphair
        external_links:
            - apphair-mysql:mysql
            - apphair-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/apphair?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    apphair-mysql:
        extends:
            file: mysql.yml
            service: apphair-mysql
    apphair-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: apphair-elasticsearch
